# this compose spins up a db2 database for development purposes
version: "3"
services:
  db2: # https://hub.docker.com/r/ibmcom/db2
    #    image: ibmcom/db2:11.5.8.0
    image: icr.io/db2_community/db2:11.5.8.0
    privileged: true
    expose:
      - 50000
    ports:
      - "50000:50000"
    environment:
      LICENSE: accept
      DBNAME: sample
      DB2INSTANCE: db2inst1
      DB2INST1_PASSWORD: change-me-please
    healthcheck:
      # Almost perfect
      test: [ "CMD", "/opt/ibm/db2/V11.5/bin/db2gcf", "-s"]
      interval: 30s
      timeout: 30s
      retries: 30
  app:
    # TODO build the image inside compose/deployment is a bad practice
    build:
      context: ../../
      dockerfile: ./src/infrastructure/Dockerfile
    expose:
      - 7070
    ports:
      - "7071:7070"
    environment:
      APP_PROFILE: compose
    depends_on:
      db2:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      # Almost perfect
      test: [ "CMD", "wget", "-S", "--spider", "http://127.0.0.1:7070/check"]
      interval: 30s
      timeout: 30s
      retries: 30

