# this compose spins up a db2 database for development purposes
version: "3"
services:
  db2: # https://hub.docker.com/r/ibmcom/db2
#    image: ibmcom/db2:11.5.8.0
    image: icr.io/db2_community/db2:11.5.8.0
    privileged: true
    expose:
      - 50000
    ports:
      - "50000:50000"
    environment:
      LICENSE: accept
      DBNAME: sample
      DB2INSTANCE: db2inst1
      DB2INST1_PASSWORD: change-me-please
  app:
    build: .
    ports:
      - "7070:7070"
    expose:
      - 7070
    depends_on:
      - db2

